name: Spring Boot CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          # Optional: Add caching for better performance
          cache: 'maven'

      # 👇 THIS WAS THE PROBLEM AREA, NOW FIXED AND SEPARATED
      - name: Grant execute permission to mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean install -DskipTests
#
#      - name: Run Unit and Automation Tests
#        run: ./mvnw test